version: "3.8"

services:
  db:
    container_name: db
    image: postgres:13
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - loadtest_db:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:6.0  

  backend:
    container_name: backend
    env_file: .env
    build: 
      context: ./server
      dockerfile: Dockerfile
    # command: bash -c "while true; do sleep 1; done"
    command: /bin/sh /server/startup-reload.sh
    volumes: 
      - ./server:/server
    ports:
      - 8000:8000
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_SERVER=${POSTGRES_SERVER}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_CACHE_DB=${REDIS_CACHE_DB}

    depends_on:
      - db
      - redis


volumes:
  loadtest_db:
