version: "3.8"

services:
  db:
    container_name: db
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=loadtest
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - loadtest_db:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:6.0
    ports:
      - 6379:6379

volumes:
  loadtest_db:
