"""Add phone column to accept twilios webhook messages

Revision ID: 6865787e6271
Revises: a675c3302149
Create Date: 2020-10-09 14:06:35.977275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6865787e6271'
down_revision = 'a675c3302149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'phone')
    # ### end Alembic commands ###
