"""Add message and replies to Requests

Revision ID: 8e718fc67174
Revises: f3df2cbba1a5
Create Date: 2020-10-08 09:23:45.666639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e718fc67174'
down_revision = 'f3df2cbba1a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('message', sa.String(), nullable=True))
    op.add_column('requests', sa.Column('replies_to', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'replies_to')
    op.drop_column('requests', 'message')
    # ### end Alembic commands ###
