"""Add date_created to Requests

Revision ID: d14d612b0ad6
Revises: 26a7e96782be
Create Date: 2020-10-08 07:34:29.530883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd14d612b0ad6'
down_revision = '26a7e96782be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('date_created', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'date_created')
    # ### end Alembic commands ###
