apiVersion: v1
kind: Service
metadata:
  name: backend
  # labels:
  #   app: backend
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer