version: "3.8"

services:
  sut:
    build: .
    command: pytest
  db:
    container_name: db
    image: postgres:13
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - loadtest_db:/var/lib/postgresql/data

  backend:
    container_name: backend
    image: pablosr11/loadtest-backend:k8
    env_file: .env
    ports:
      - 8000:8000
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_SERVER=${POSTGRES_SERVER}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_CACHE_DB=${REDIS_CACHE_DB}
    depends_on:
      - db
      - redis

  redis:
    container_name: redis
    image: redis:6.0

volumes:
  loadtest_db:
