apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: pablosr11/loadtest-backend:k8
          imagePullPolicy: Always
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_SERVER
              value: "db"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: "loadtest"
          ports:
            - containerPort: 8000
