---
- name: Setup servers
  gather_facts: no
  hosts: prod
  remote_user: ubuntu
  vars:
    docker_apt_packages: ["docker-ce", "docker-ce-cli", "containerd.io"]
    docker_apt_dependecies:
      [
        "apt-transport-https",
        "curl",
        "ca-certificates",
        "gnupg-agent",
        "software-properties-common",
        "python3-pip",
      ]
    docker_apt_key_url: https://download.docker.com/linux/ubuntu/gpg
    ubuntu_release: "focal" # output of $(lsb_release -cs)

  tasks:
    ###
    ### UPDATE APT PACKAGES
    ###
    - name: Update index and Upgrade all packages to the latest version
      become: yes
      apt:
        upgrade: full
        state: present
        update_cache: yes

    ###
    ### INSTALL DOCKER PACKAGES + DOCKER ENGINE
    ###
    - name: Instal docker dependencies
      become: yes
      apt:
        name: "{{ docker_apt_dependecies }}"
        state: present
        update_cache: yes

    - name: Add Docker GPG apt Key
      become: yes
      apt_key:
        url: "{{ docker_apt_key_url }}"
        state: present

    - name: Add Docker apt Repository and Update index
      become: yes
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu {{ ubuntu_release }} stable
        state: present
        update_cache: yes

    - name: Install Docker Engine packages
      become: yes
      apt:
        name: "{{ docker_apt_packages }}"
        state: present

    - name: Install Docker Module for Python
      become: yes # so docker container has acces to python3
      pip:
        name: docker
        state: present

- name: BACKEND DEPLOYMENT
  gather_facts: no
  hosts: backend
  remote_user: ubuntu
  tasks:
    ### Check required variables
    - name: Check required variables are defined correctly
      assert:
        that:
          - vars[item] is defined and vars[item] != ""
        quiet: yes
      with_items:
        - db_server
        - db_name
        - db_user
        - db_pass
        - db_port
        - backend_image
        - backend_tag
        - backend_exposed_port

    ###
    ### APP DEPLOYMENT
    ###
    - name: Deploy backend
      become: yes
      docker_container:
        name: web
        container_default_behavior: compatibility
        pull: yes # to pick up new image
        image: "{{ backend_image }}:{{ backend_tag }}"
        ports:
          - "{{ backend_exposed_port }}"
        env:
          POSTGRES_USER: "{{ db_user }}"
          POSTGRES_PASSWORD: "{{ db_pass }}"
          POSTGRES_SERVER: "{{ db_server }}"
          POSTGRES_PORT: "{{ db_port }}"
          POSTGRES_DB: "{{ db_name }}"

- name: FRONTEND DEPLOYMENT
  gather_facts: no
  hosts: frontend
  remote_user: ubuntu

  tasks:
    ### Check required variables
    - name: Check required variables are defined correctly
      assert:
        that:
          - vars[item] is defined and vars[item] != ""
        quiet: yes
      with_items:   
        - frontend_image
        - frontend_tag
        - frontend_exposed_port

    ###
    ### APP DEPLOYMENT
    ###
    - name: Deploy frontend
      become: yes
      docker_container:
        name: front
        container_default_behavior: compatibility
        pull: yes # to pick up new image
        image: "{{ frontend_image }}:{{ frontend_tag }}"
        ports:
          - "{{ frontend_exposed_port }}"
