name: Deploy

on:
  repository_dispatch:
    types: deployment
  deployment:

env:
  GKE_CLUSTER_NAME: learn-k8s-in-gke-gke
  GKE_CLUSTER_REGION: europe-west2-b
  HELM_RELEASE_NAME: test

jobs:

  ## this should only run after a change is merged (so has passed tests etc)
  debug:
    runs-on: ubuntu-latest
    if: github.event.client_payload
    steps:
      # RUN TESTS ETC
      - name: received the deployment?
        run: echo ${{ github.event.client_payload.unit }}
      
      - run: echo ${{ github.event.client_payload.ref }} 
      - run: echo ${{ github.event.client_payload.sha }} 
      - run: echo ${{ github.event_name }} 
      
      - run: exit 1

  deployment:

    runs-on: ubuntu-latest
    needs: debug # remove

    steps:
      - uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      # Install helm - Ideally we would do this once to avoid issues with helm versions/save time
      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      # Deploy the Docker image to the GKE cluster
      - name: Deploy
        run: |
          gcloud container clusters get-credentials $GKE_CLUSTER_NAME \
            --region $GKE_CLUSTER_REGION
          helm upgrade --install $HELM_RELEASE_NAME k8s/load-chart